#
# Copyright (C) 2019 Authlete, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the License for the specific
# language governing permissions and limitations under the
# License.


#==================================================
# VARIABLES
#==================================================
PYTHON = python3


#==================================================
# TARGETS
#==================================================
.PHONY: _default clean clean-python help run shell


_default: help


clean: clean-python


clean-python:
	@find . -name "__pycache__" -prune -exec rm -rf '{}' \;
	@find . -name "*.py[cdo]" -exec rm -rf '{}' \;


help:
	@printf '%s\n' \
	"clean        - removes generated files." \
	"clean-python - removes files generated by python." \
	"help         - shows this help text." \
	"run          - starts the web servier for development." \
	"shell        - starts a Python shell."


run:
	$(PYTHON) manage.py runserver


shell:
	$(PYTHON) manage.py shell
